version: '3.8'

services:
  app:
    build: .
    image: nestjs-fuel
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - uploads:/usr/src/app/uploads

  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app

volumes:
  uploads:
    driver: local